[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/about/"
  to = "/dr-jelena-djurovic/"
  status = 301
  force = true

[[redirects]]
  from = "/sr/about/"
  to = "/sr/dr-jelena-djurovic/"
  status = 301
  force = true
