backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/assets/blog"
public_folder: "/assets/blog"

collections:
  - name: "blog"
    label: "Blog Post"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPostLayout.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Author", name: "author", widget: "string", default: "Dr. Jelena Djurovic"}
      - {label: "Introduction Outline", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
